package network

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

// DefaultFallbackDNS contains reliable upstream public resolvers used when no routable host servers exist.
var DefaultFallbackDNS = []string{"1.1.1.1", "8.8.8.8"}

// ResolveDNSList determines the effective DNS servers.
// If custom servers are specified, they are validated and used.
// Otherwise, it inspects the host /etc/resolv.conf, filters out loopback resolvers
// (e.g., 127.0.0.53 from systemd-resolved), and falls back to DefaultFallbackDNS if none remain.
func ResolveDNSList(custom []string) []string {
	var validCustom []string
	for _, s := range custom {
		s = strings.TrimSpace(s)
		if ip := net.ParseIP(s); ip != nil {
			validCustom = append(validCustom, ip.String())
		}
	}
	if len(validCustom) > 0 {
		return validCustom
	}

	hostDNS := parseHostResolvConf("/etc/resolv.conf")
	if len(hostDNS) > 0 {
		return hostDNS
	}

	return DefaultFallbackDNS
}

// parseHostResolvConf extracts non-loopback nameservers from a resolv.conf file.
func parseHostResolvConf(path string) []string {
	file, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer func() {
		_ = file.Close()
	}()

	var servers []string
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == "nameserver" {
			ip := net.ParseIP(fields[1])
			if ip != nil && !ip.IsLoopback() {
				servers = append(servers, ip.String())
			}
		}
	}

	return servers
}

// InjectResolvConf writes /etc/resolv.conf inside the container rootfs.
func InjectResolvConf(rootfs string, dnsServers []string) error {
	effective := ResolveDNSList(dnsServers)

	etcDir := filepath.Join(rootfs, "etc")
	if err := os.MkdirAll(etcDir, 0755); err != nil {
		return fmt.Errorf("failed to create /etc in rootfs: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by gojail\n")
	for _, ns := range effective {
		fmt.Fprintf(&sb, "nameserver %s\n", ns)
	}

	resolvPath := filepath.Join(etcDir, "resolv.conf")
	// Remove any existing file or dangling symlink first (e.g. systemd-resolved stub)
	_ = os.Remove(resolvPath)

	if err := os.WriteFile(resolvPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write resolv.conf: %w", err)
	}

	return nil
}
